#!/usr/bin/perl

open OUTFILE, ">$ARGV[0]_mod";
select OUTFILE;
while(<>){
	if (/^>/){
		my ($acc,$species,$desc) = split(/\|/, $_);
		#print "$acc\n";
		$acc =~ s/>(.+)\s/$1/g;
		$species =~ s/\s/_/g;
		print ">$species |$acc|$desc";
		$count++;
	}else{
		print;
	}
}
close OUTFILE;
select STDOUT;
print "$count sequences\n";
	
