#!/usr/bin/perl
use strict;
use warnings;

print "tax_name	Species	Genus	Family	Order NULL	Class	Sub-Phylum	Phylum	SuperKingdom Life-Type\n";
while (<>){
	chomp($_);
	my @line = split(/\t/, $_);

	my $taxon= $line[4];
	$taxon =~ s/\s/_/g;

	my $strat = $line[6];
	$strat =~ s/\s/\t/g;

	print "$taxon\t$strat\n";
}
